Handle Different Names in DEPENDENCIES

diff --git a/match_deps.sh.in b/match_deps.sh.in
--- a/match_deps.sh.in
+++ b/match_deps.sh.in
@@ -179,14 +179,16 @@ rm -f dep_001
 
 for dep in $(ls dep_*)
 do
-    NAME="$(cat $dep | head -n 1)"
     URI="$(cat $dep | grep URI | cut -d' ' -f2)"
+    NAME="$(basename $URI)"
+    NAME="${NAME%.*}"
     BRANCH="$(cat $dep | grep branch | cut -d' ' -f2)"
     REV="$(cat $dep | grep revision | cut -d' ' -f2)"
 
     if [ -d "${NAME}" ]
     then
 	pushd "${NAME}" >/dev/null 2>&1
+	git fetch --all --prune >/dev/null 2>&1
 	git checkout "${BRANCH}" >/dev/null 2>&1 || \
 	    (echo "--> $BRANCH doesn't exist in $NAME!" ; exit 1)
 	US="$(git branch -vv | grep '\*' | awk '{ print $4 }')"
@@ -195,6 +197,14 @@ do
 	if [ "${US}" != "origin/${BRANCH}" ]
 	then
 	    echo "--> ${NAME}: ${BRANCH} is not set to sync with ${US}!"
+	    exit 1
+	fi
+
+	git reset --hard "origin/${BRANCH}" >/dev/null 2>&1
+
+	if [ $? -ne 0 ]
+	then
+	    echo "--> Unable to reset to origin/${BRANCH}!"
 	    exit 1
 	fi
 
@@ -209,7 +219,11 @@ do
     else
 	git clone "${URI}" "${NAME}"
 	pushd "${NAME}" >/dev/null 2>&1
-	git checkout --track -b "${BRANCH}" origin/"${BRANCH}"
+	CURRENT_BRANCH="$(git branch | cut -d' ' -f2)"
+	if [ "${CURRENT_BRANCH}" != "${BRANCH}" ]
+	then
+	    git checkout --track -b "${BRANCH}" origin/"${BRANCH}"
+	fi
 	git reset --hard "${REV}"
 	popd >/dev/null 2>&1
     fi
